#!/usr/bin/env node
// GENERATED by `tooling/build-cli.ts` in the niiko monorepo — DO NOT EDIT BY HAND.
// Plan `6c3240a7b22d`. A new action shows up here on regeneration; none is added by editing this file.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

type Action = {
  action: string;
  version: number;
  scope: string;
  purpose: string;
  refusalReasons: readonly string[];
  input: Record<string, unknown>;
  output: Record<string, unknown>;
};

/** The catalog, exactly as it was in plan `6c3240a7b22d`. */
const CATALOG: readonly Action[] = [
  {
    "action": "miira.lead_create",
    "version": 1,
    "scope": "miira.lead_create@1",
    "purpose": "Creates a new lead in the workspace CRM from its contact details. If a matching one already exists it is not duplicated: the reply is `ambiguous` with the candidates.",
    "refusalReasons": [
      "honeypot",
      "invalid_email",
      "disposable_email",
      "invalid_identity"
    ],
    "input": {
      "type": "object",
      "properties": {
        "submissionId": {
          "type": "string",
          "format": "uuid"
        },
        "source": {
          "type": "string",
          "enum": [
            "web_form",
            "referral",
            "api",
            "import",
            "event",
            "other"
          ]
        },
        "name": {
          "type": "string",
          "maxLength": 256
        },
        "email": {
          "type": "string",
          "format": "email",
          "maxLength": 320
        },
        "phone": {
          "type": "string",
          "maxLength": 40
        },
        "fields": {
          "type": "object",
          "additionalProperties": true
        },
        "consent": {
          "type": "object",
          "properties": {
            "email": {
              "type": "boolean"
            },
            "whatsapp": {
              "type": "boolean"
            },
            "source": {
              "type": "string",
              "enum": [
                "api",
                "web_form",
                "verbal",
                "llamada",
                "visita",
                "imported"
              ]
            }
          },
          "required": [
            "source"
          ],
          "additionalProperties": true
        }
      },
      "required": [
        "submissionId",
        "source"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "outcome": {
          "type": "string",
          "enum": [
            "created",
            "existing",
            "ambiguous",
            "rejected"
          ]
        },
        "clientId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "reason": {
          "anyOf": [
            {
              "type": "string",
              "enum": [
                "honeypot",
                "invalid_email",
                "disposable_email",
                "invalid_identity"
              ]
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "outcome",
        "clientId",
        "reason"
      ]
    }
  },
  {
    "action": "crm.call_logged",
    "version": 1,
    "scope": "crm.call_logged@1",
    "purpose": "Logs what was discussed in a call on a client's record, naming the client; optionally creates the follow-up with its date. Reads nothing and calls no one.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "summary": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4000
        },
        "followUp": {
          "type": "object",
          "properties": {
            "what": {
              "type": "string",
              "minLength": 1,
              "maxLength": 500
            },
            "dueAt": {
              "type": "string",
              "format": "date-time"
            }
          },
          "required": [
            "dueAt"
          ],
          "additionalProperties": true
        }
      },
      "required": [
        "client",
        "summary"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "activityId": {
          "type": "string"
        },
        "followUpId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "clientId",
        "clientName",
        "activityId",
        "followUpId"
      ]
    }
  },
  {
    "action": "crm.owner_assigned",
    "version": 1,
    "scope": "crm.owner_assigned@1",
    "purpose": "Changes who owns a client, naming the client and the team member (by name or email). If either is ambiguous it refuses with the list.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "persona_no_encontrada",
      "persona_ambigua",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "owner": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": [
        "client",
        "owner"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "ownerUserId": {
          "type": "string"
        },
        "ownerName": {
          "type": "string"
        }
      },
      "required": [
        "clientId",
        "clientName",
        "ownerUserId",
        "ownerName"
      ]
    }
  },
  {
    "action": "crm.stage_moved",
    "version": 1,
    "scope": "crm.stage_moved@1",
    "purpose": "Moves a client's open deal to another pipeline stage, naming the client and the stage. Creates no deals: with no open deal it refuses, and with several it refuses with the list.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "sin_negocio_abierto",
      "varios_negocios",
      "etapa_no_encontrada",
      "negocio_cerrado",
      "ya_en_esa_etapa",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "stage": {
          "type": "string",
          "minLength": 1,
          "maxLength": 120
        },
        "lostReason": {
          "type": "string",
          "maxLength": 500
        }
      },
      "required": [
        "client",
        "stage"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "dealId": {
          "type": "string"
        },
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "stageName": {
          "type": "string"
        },
        "won": {
          "type": "boolean"
        },
        "firstWon": {
          "type": "boolean"
        }
      },
      "required": [
        "dealId",
        "clientId",
        "clientName",
        "stageName",
        "won",
        "firstWon"
      ]
    }
  },
  {
    "action": "kiipu.invoice_proposed",
    "version": 1,
    "scope": "kiipu.invoice_proposed@1",
    "purpose": "Prepares an invoice as a DRAFT for a client named by name, with its lines and taxes. Does NOT issue it, does NOT number it and does NOT count as debt: a person reviews and issues it in Kiipu. Does not create the client if it does not exist.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "lines": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "concept": {
                "type": "string",
                "minLength": 1,
                "maxLength": 500
              },
              "quantity": {
                "type": "string",
                "pattern": "^(?!0+(?:\\.0+)?$)\\d+(?:\\.\\d{1,3})?$"
              },
              "unitPriceUsd": {
                "type": "string",
                "pattern": "^\\d+(\\.\\d{1,2})?$"
              },
              "tax": {
                "type": "string",
                "enum": [
                  "exempt",
                  "itbms_7",
                  "itbms_10",
                  "itbms_15"
                ],
                "default": "exempt"
              }
            },
            "required": [
              "concept",
              "quantity",
              "unitPriceUsd"
            ],
            "additionalProperties": true
          }
        },
        "dueAt": {
          "type": "string",
          "format": "date-time"
        },
        "series": {
          "type": "string",
          "pattern": "^[A-Za-z0-9-]{1,12}$"
        }
      },
      "required": [
        "client",
        "lines"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "invoiceId": {
          "type": "string"
        },
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "status": {
          "const": "draft"
        },
        "subtotalUsd": {
          "type": "string"
        },
        "taxUsd": {
          "type": "string"
        },
        "totalUsd": {
          "type": "string"
        },
        "dueAt": {
          "type": "string"
        },
        "series": {
          "type": "string"
        },
        "issueAt": {
          "const": "/kiipu/facturas"
        }
      },
      "required": [
        "invoiceId",
        "clientId",
        "clientName",
        "status",
        "subtotalUsd",
        "taxUsd",
        "totalUsd",
        "dueAt",
        "series",
        "issueAt"
      ]
    }
  },
  {
    "action": "crm.task_created",
    "version": 1,
    "scope": "crm.task_created@1",
    "purpose": "Creates a reminder (a task with date and time) on a client named by name. Does not log a call: that is crm.call_logged. Does not create the client if it does not exist.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "what": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500
        },
        "dueAt": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "client",
        "what",
        "dueAt"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "taskId": {
          "type": "string"
        },
        "dueAt": {
          "type": "string"
        }
      },
      "required": [
        "clientId",
        "clientName",
        "taskId",
        "dueAt"
      ]
    }
  },
  {
    "action": "crm.deal_created",
    "version": 1,
    "scope": "crm.deal_created@1",
    "purpose": "Opens a new deal in the pipeline for a client named by name, with a title, an optional value in USD, an optional stage (by name; without it, the first one) and an optional owner. Does not check for other open deals: it returns how many remain so a duplicate is visible. Does not win or lose it: that is crm.stage_moved.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "etapa_no_encontrada",
      "etapa_cerrada",
      "persona_no_encontrada",
      "persona_ambigua",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "valueUsd": {
          "type": "string",
          "pattern": "^\\d+(\\.\\d{1,2})?$"
        },
        "stage": {
          "type": "string",
          "minLength": 1,
          "maxLength": 120
        },
        "owner": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": [
        "client",
        "title"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "dealId": {
          "type": "string"
        },
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "valueUsd": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "stageName": {
          "type": "string"
        },
        "ownerName": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "openDeals": {
          "type": "integer",
          "minimum": 1
        }
      },
      "required": [
        "dealId",
        "clientId",
        "clientName",
        "title",
        "valueUsd",
        "stageName",
        "ownerName",
        "openDeals"
      ]
    }
  },
  {
    "action": "crm.note_added",
    "version": 1,
    "scope": "crm.note_added@1",
    "purpose": "Saves a note on a client's record, naming the client: something to know next time, with no call and no date. For a call use crm.call_logged; for a dated reminder, crm.task_created.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "note": {
          "type": "string",
          "minLength": 1,
          "maxLength": 2000
        }
      },
      "required": [
        "client",
        "note"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "noteId": {
          "type": "string"
        }
      },
      "required": [
        "clientId",
        "clientName",
        "noteId"
      ]
    }
  },
  {
    "action": "crm.contact_added",
    "version": 1,
    "scope": "crm.contact_added@1",
    "purpose": "Adds a person (name, and optionally email, phone and role) to a client's record, naming the client. Does not make them the primary contact and does not create the client. If someone with that email or phone already existed, the reply says so but does not block it.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "email": {
          "type": "string",
          "format": "email",
          "maxLength": 320
        },
        "phone": {
          "type": "string",
          "minLength": 5,
          "maxLength": 40
        },
        "role": {
          "type": "string",
          "minLength": 1,
          "maxLength": 120
        }
      },
      "required": [
        "client",
        "name"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "contactId": {
          "type": "string"
        },
        "possibleDuplicate": {
          "type": "boolean"
        }
      },
      "required": [
        "clientId",
        "clientName",
        "contactId",
        "possibleDuplicate"
      ]
    }
  },
  {
    "action": "miira.broadcast_quoted",
    "version": 1,
    "scope": "miira.broadcast_quoted@1",
    "purpose": "Quotes sending the SAME WhatsApp message to several clients named by name (up to 50). Sends NOTHING: per client, it says whether the text goes as-is (24-hour window open, free), whether an approved template is needed and what it costs, or why that client cannot be messaged. Returns a signed quote valid for 15 minutes; to send, call miira.broadcast_sent with it. Show the quote to the person first.",
    "refusalReasons": [
      "plantilla_invalida",
      "tarifas_vencidas",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "clients": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200
          }
        },
        "message": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096
        },
        "template": {
          "type": "string",
          "minLength": 1,
          "maxLength": 512
        },
        "templateValues": {
          "type": "array",
          "items": {
            "type": "string",
            "maxLength": 1024
          }
        }
      },
      "required": [
        "clients",
        "message"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "rows": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "client": {
                "type": "string"
              },
              "clientId": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "clientName": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "outcome": {
                "type": "string",
                "enum": [
                  "free_text",
                  "template",
                  "needs_template",
                  "no_phone",
                  "suppressed",
                  "consent_revoked",
                  "no_marketing_consent",
                  "quiet_hours",
                  "not_found",
                  "ambiguous",
                  "too_many"
                ]
              },
              "costUsd": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "candidates": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "client",
              "clientId",
              "clientName",
              "outcome",
              "costUsd"
            ],
            "additionalProperties": true
          }
        },
        "totals": {
          "type": "object",
          "properties": {
            "freeText": {
              "type": "integer"
            },
            "template": {
              "type": "integer"
            },
            "skipped": {
              "type": "integer"
            },
            "costUsd": {
              "type": "string"
            }
          },
          "required": [
            "freeText",
            "template",
            "skipped",
            "costUsd"
          ],
          "additionalProperties": true
        },
        "quote": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "expiresAt": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "rows",
        "totals",
        "quote",
        "expiresAt"
      ]
    }
  },
  {
    "action": "miira.broadcast_sent",
    "version": 1,
    "scope": "miira.broadcast_sent@1",
    "purpose": "Sends the WhatsApp broadcast quoted by miira.broadcast_quoted, exactly to whom and how the quote said. If anything changed (window, consent, rate) it refuses with a new quote to confirm again. Costs money when templates are involved: do not call it without the person having seen the cost.",
    "refusalReasons": [
      "presupuesto_invalido",
      "presupuesto_vencido",
      "presupuesto_cambiado",
      "plantilla_invalida",
      "tarifas_vencidas",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "quote": {
          "type": "string",
          "minLength": 1,
          "maxLength": 65536
        }
      },
      "required": [
        "quote"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "queued": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "clientId": {
                "type": "string"
              },
              "clientName": {
                "type": "string"
              },
              "mode": {
                "type": "string",
                "enum": [
                  "free_text",
                  "template"
                ]
              },
              "outboxId": {
                "type": "string"
              }
            },
            "required": [
              "clientId",
              "clientName",
              "mode",
              "outboxId"
            ],
            "additionalProperties": true
          }
        },
        "costUsd": {
          "type": "string"
        }
      },
      "required": [
        "queued",
        "costUsd"
      ]
    }
  },
  {
    "action": "kiipu.draft_voided",
    "version": 1,
    "scope": "kiipu.draft_voided@1",
    "purpose": "Voids a DRAFT invoice (one created with kiipu.invoice_proposed and not yet issued), by its id or by the client's name when it is their only draft. Does not void issued invoices: that is for a person in Kiipu.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "borrador_no_encontrado",
      "varios_borradores",
      "no_es_borrador",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "invoiceId": {
          "type": "string",
          "format": "uuid"
        },
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": []
    },
    "output": {
      "type": "object",
      "properties": {
        "invoiceId": {
          "type": "string"
        },
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "totalUsd": {
          "type": "string"
        },
        "status": {
          "const": "void"
        }
      },
      "required": [
        "invoiceId",
        "clientId",
        "clientName",
        "totalUsd",
        "status"
      ]
    }
  },
  {
    "action": "kiipu.payment_reported",
    "version": 1,
    "scope": "kiipu.payment_reported@1",
    "purpose": "Leaves in the Kiipu approval queue the notice that a client (by name) paid a given amount of an open invoice. Does NOT apply the payment and touches no balances: a person checks it against the bank and applies it. If the client has several open invoices the number must be given.",
    "refusalReasons": [
      "cliente_no_encontrado",
      "cliente_ambiguo",
      "demasiados_clientes",
      "sin_factura_abierta",
      "varias_facturas",
      "factura_no_encontrada",
      "sin_permiso"
    ],
    "input": {
      "type": "object",
      "properties": {
        "client": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "amountUsd": {
          "type": "string",
          "pattern": "^\\d+(\\.\\d{1,2})?$"
        },
        "invoice": {
          "type": "string",
          "minLength": 1,
          "maxLength": 40
        }
      },
      "required": [
        "client",
        "amountUsd"
      ]
    },
    "output": {
      "type": "object",
      "properties": {
        "submissionId": {
          "type": "string"
        },
        "clientId": {
          "type": "string"
        },
        "clientName": {
          "type": "string"
        },
        "invoiceId": {
          "type": "string"
        },
        "invoiceNumber": {
          "type": "string"
        },
        "outstandingUsd": {
          "type": "string"
        },
        "declaredUsd": {
          "type": "string"
        },
        "status": {
          "const": "received"
        },
        "reviewAt": {
          "const": "/kiipu/aprobaciones"
        }
      },
      "required": [
        "submissionId",
        "clientId",
        "clientName",
        "invoiceId",
        "invoiceNumber",
        "outstandingUsd",
        "declaredUsd",
        "status",
        "reviewAt"
      ]
    }
  }
];

type Config = { url: string; apiKey: string };
const CONFIG_PATH = join(process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config"), "niiko", "config.json");

function readConfig(): Config | null {
  if (!existsSync(CONFIG_PATH)) return null;
  try {
    const c = JSON.parse(readFileSync(CONFIG_PATH, "utf8")) as Partial<Config>;
    return typeof c.url === "string" && typeof c.apiKey === "string" ? { url: c.url, apiKey: c.apiKey } : null;
  } catch {
    return null;
  }
}

/** The key: `--key`, then `NIIKO_API_KEY`, then the saved one. In that order, so a script can send without
 *  touching the person's configuration. It is never printed. */
function credentials(args: Map<string, string>): Config | null {
  const saved = readConfig();
  const url = args.get("url") ?? process.env.NIIKO_URL ?? saved?.url ?? "https://niiko.org";
  const apiKey = args.get("key") ?? process.env.NIIKO_API_KEY ?? saved?.apiKey;
  return apiKey ? { url: url.replace(/\/+$/, ""), apiKey } : null;
}

function exit(code: number, body: unknown): never {
  process.stdout.write(JSON.stringify(body, null, 2) + "\n");
  process.exit(code);
}

/** `--a b` and `--a=b`. Anything not starting with `--` is positional. */
function parse(argv: string[]): { positional: string[]; args: Map<string, string> } {
  const positional: string[] = [];
  const args = new Map<string, string>();
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (a.startsWith("--")) {
      const [k, v] = a.slice(2).split("=", 2);
      if (v !== undefined) args.set(k!, v);
      else if (i + 1 < argv.length && !argv[i + 1]!.startsWith("--")) args.set(k!, argv[++i]!);
      else args.set(k!, "");
    } else positional.push(a);
  }
  return { positional, args };
}

function readInput(args: Map<string, string>): unknown {
  const raw = args.get("input");
  let text: string;
  if (raw === undefined) {
    if (process.stdin.isTTY) exit(1, { error: "missing input: --input '{…}', --input @file, or stdin" });
    text = readFileSync(0, "utf8");
  } else if (raw.startsWith("@")) text = readFileSync(raw.slice(1), "utf8");
  else text = raw;
  try {
    return JSON.parse(text);
  } catch {
    return exit(1, { error: "input is not valid JSON" });
  }
}

function uuid(): string {
  return globalThis.crypto.randomUUID();
}

const HELP = `niiko — the niiko actions API from the terminal (plan 6c3240a7b22d)

  niiko login --url https://niiko.org --key nk_…   saves the key to ${CONFIG_PATH}
  niiko actions                                    the open actions, with their purpose
  niiko describe <action>                          input, output and refusal reasons of one action
  niiko run <action> --input '{…}'                 exercises an action (also --input @file or stdin)
      [--idempotency-key K] [--key nk_…] [--url …]

Exit codes of \`run\`: 0 done · 2 refused (the reason is in the output) · 3 waiting for a signature · 1 error.
The key is also read from NIIKO_API_KEY and the URL from NIIKO_URL.`;

async function main(): Promise<void> {
  const { positional, args } = parse(process.argv.slice(2));
  const cmd = positional[0];

  if (!cmd || cmd === "help" || args.has("help")) {
    process.stdout.write(HELP + "\n");
    process.exit(0);
  }

  if (cmd === "login") {
    const apiKey = args.get("key") ?? process.env.NIIKO_API_KEY;
    if (!apiKey) exit(1, { error: "missing --key nk_… (or NIIKO_API_KEY)" });
    const url = (args.get("url") ?? process.env.NIIKO_URL ?? "https://niiko.org").replace(/\/+$/, "");
    mkdirSync(join(CONFIG_PATH, ".."), { recursive: true });
    writeFileSync(CONFIG_PATH, JSON.stringify({ url, apiKey }, null, 2) + "\n", { mode: 0o600 });
    // Say WHERE it went and the prefix, never the whole key: a terminal is a history.
    exit(0, { saved: CONFIG_PATH, url, key: apiKey.slice(0, 7) + "…" });
  }

  if (cmd === "actions") {
    exit(0, CATALOG.map((a) => ({ action: a.action, version: a.version, scope: a.scope, purpose: a.purpose })));
  }

  if (cmd === "describe") {
    const id = positional[1];
    const a = CATALOG.find((x) => x.action === id);
    if (!a) exit(1, { error: `unknown action \`${id}\``, available: CATALOG.map((x) => x.action) });
    exit(0, a);
  }

  if (cmd === "run") {
    const id = positional[1];
    const a = CATALOG.find((x) => x.action === id);
    if (!a) exit(1, { error: `unknown action \`${id}\``, available: CATALOG.map((x) => x.action) });
    const cred = credentials(args);
    if (!cred) exit(1, { error: "no key: niiko login --key nk_…, or NIIKO_API_KEY, or --key" });
    const input = readInput(args);
    const key = args.get("idempotency-key") ?? uuid();

    let r: Response;
    try {
      r = await fetch(`${cred.url}/api/v1/actions/${a.action}`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${cred.apiKey}`,
          "Content-Type": "application/json",
          // Always with a key: without one a retry after a timeout duplicates the effect, and the server requires it.
          "Idempotency-Key": key,
          "User-Agent": "niiko-cli/0.1.1",
        },
        body: JSON.stringify(input),
      });
    } catch (e) {
      exit(1, { error: "could not connect", detail: String(e), url: cred.url });
    }
    const body: unknown = await r.json().catch(() => null);
    const status = (body as { status?: string } | null)?.status;
    // The idempotency key travels in the output even if the server does not echo it: it is what lets you retry
    // EXACTLY the same thing if the terminal died before reading the reply.
    const out = typeof body === "object" && body !== null ? { ...body, idempotencyKey: (body as { idempotencyKey?: string }).idempotencyKey ?? key } : { http: r.status, body };
    if (status === "done") exit(0, out);
    if (status === "pending_approval") exit(3, out);
    if (status === "refused") exit(2, out);
    exit(1, { error: `unexpected response (HTTP ${r.status})`, ...out });
  }

  exit(1, { error: `unknown command: ${cmd}`, help: "niiko help" });
}

main().catch((e) => exit(1, { error: String(e) }));
